#!/usr/bin/python

import smbus
import time
import sys
import struct

# bytes to read/transmit at once
CHUNKSIZE = 32

# check number of arguments
if len(sys.argv) != 2:
    print("Expected single argument")
    sys.exit()

# get I2C bus
bus = smbus.SMBus(1)

# device address
ADDRESS = 0x0F

# open binary file
try:
    f = open(sys.argv[1],"rb")
except IOError:
    print("Could not open file")
    sys.exit()

# iterate through file by chunks until EOF
for chunk in iter(lambda: f.read(CHUNKSIZE), ''):
    # convert from string to int
    chunk = struct.unpack('H'*CHUNKSIZE/2,chunk)
    # send out chunk over i2c
    print(type(chunk))
    print(chunk)
    bus.write_i2c_block_data(ADDRESS,len(chunk),chunk)

# close file smbus and exit
f.close()
bus.close()
sys.exit()
